FROM python:3-alpine AS build
RUN apk add build-base
RUN apk update && apk upgrade && apk add --no-cache bash git openssh
COPY ./mkdocs/ /mkdocs/
WORKDIR /mkdocs/
RUN pip install mkdocs mkdocs-material
RUN mkdocs gh-deploy
